[tool.poetry]
name = "mylibrary"
version = "0.0.1"
description = "Website."
authors = ["Juan F. Imbet"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

